# Generated by Django 5.2.9 on 2026-01-03 22:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backup',
            options={'ordering': ['-created_at'], 'verbose_name': 'Бэкап', 'verbose_name_plural': 'Бэкапы'},
        ),
        migrations.AlterModelOptions(
            name='mod',
            options={'verbose_name': 'Мод', 'verbose_name_plural': 'Моды'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterModelOptions(
            name='plugin',
            options={'verbose_name': 'Плагин', 'verbose_name_plural': 'Плагины'},
        ),
        migrations.AlterModelOptions(
            name='resourceusage',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Использование ресурсов', 'verbose_name_plural': 'Использование ресурсов'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сервер', 'verbose_name_plural': 'Серверы'},
        ),
        migrations.AlterModelOptions(
            name='serverevent',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='serverlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Лог сервера', 'verbose_name_plural': 'Логи серверов'},
        ),
        migrations.AlterModelOptions(
            name='serversettings',
            options={'verbose_name': 'Настройки сервера', 'verbose_name_plural': 'Настройки серверов'},
        ),
        migrations.AlterModelOptions(
            name='serverstatistics',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Статистика сервера', 'verbose_name_plural': 'Статистика серверов'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AddField(
            model_name='backup',
            name='size_bytes',
            field=models.BigIntegerField(default=0, verbose_name='Размер (байты)'),
        ),
        migrations.AddField(
            model_name='mod',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Включен'),
        ),
        migrations.AddField(
            model_name='mod',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plugin',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Включен'),
        ),
        migrations.AddField(
            model_name='plugin',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='memory',
            field=models.CharField(default='2G', help_text='Например: 1G, 2G, 4G, 8G', max_length=10, verbose_name='Выделенная память'),
        ),
        migrations.AddField(
            model_name='server',
            name='minecraft_version',
            field=models.CharField(default='1.20.1', help_text='Например: 1.20.1, 1.19.4, 1.18.2', max_length=20, verbose_name='Версия Minecraft'),
        ),
        migrations.AddField(
            model_name='server',
            name='server_type',
            field=models.CharField(choices=[('VANILLA', 'Vanilla'), ('PAPER', 'Paper'), ('SPIGOT', 'Spigot'), ('BUKKIT', 'Bukkit'), ('FORGE', 'Forge'), ('FABRIC', 'Fabric'), ('PURPUR', 'Purpur'), ('FOLIA', 'Folia'), ('PUFFERFISH', 'Pufferfish'), ('AIRPLANE', 'Airplane'), ('MOHIST', 'Mohist (Forge + Bukkit)'), ('CATSERVER', 'CatServer (Forge + Bukkit)')], default='PAPER', max_length=20, verbose_name='Тип ядра'),
        ),
        migrations.AddField(
            model_name='server',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AddField(
            model_name='serversettings',
            name='difficulty',
            field=models.CharField(choices=[('peaceful', 'Мирный'), ('easy', 'Легкий'), ('normal', 'Нормальный'), ('hard', 'Сложный')], default='normal', max_length=20, verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='serversettings',
            name='gamemode',
            field=models.CharField(choices=[('survival', 'Выживание'), ('creative', 'Творчество'), ('adventure', 'Приключение'), ('spectator', 'Наблюдатель')], default='survival', max_length=20, verbose_name='Режим игры'),
        ),
        migrations.AddField(
            model_name='serversettings',
            name='online_mode',
            field=models.BooleanField(default=True, verbose_name='Online mode'),
        ),
        migrations.AddField(
            model_name='serversettings',
            name='pvp_enabled',
            field=models.BooleanField(default=True, verbose_name='PVP'),
        ),
        migrations.AlterField(
            model_name='server',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='server',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Онлайн'),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название сервера'),
        ),
        migrations.AlterField(
            model_name='server',
            name='port',
            field=models.IntegerField(verbose_name='Порт'),
        ),
        migrations.AlterField(
            model_name='serversettings',
            name='max_players',
            field=models.IntegerField(default=20, verbose_name='Макс. игроков'),
        ),
        migrations.AlterField(
            model_name='serversettings',
            name='motd',
            field=models.CharField(default='Welcome to the server!', max_length=100, verbose_name='MOTD'),
        ),
        migrations.AlterField(
            model_name='serversettings',
            name='whitelist_enabled',
            field=models.BooleanField(default=False, verbose_name='Белый список'),
        ),
    ]
